{% set name = "skore" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: 28a34803660f22802cdb2717d449a84483c9e758af1a30e2764b6fef2c9bfaae

build:
  entry_points:
    - skore = skore.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - diskcache
    - fastapi
    - joblib
    - matplotlib-base
    - numpy
    - orjson
    - pandas
    - platformdirs
    - plotly >=5,<6
    - psutil
    - pyarrow
    - rich
    - scikit-learn
    # Need to pin sqlite for compatibility reason with diskcache
    # cf. https://github.com/probabl-ai/skore/issues/1353
    - sqlite <3.49
    - skops
    - uvicorn

test:
  imports:
    - skore
  commands:
    - pip check
    - skore --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - MarieSacksick
    - sylvaincom
    - thomass-dev
    - tuscland
