{% set name = "skore" %}
{% set version = "0.15.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: d6699718aec1aef8136ca6184e047b408866e2955979f0846757aa1c414ac259

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - IPython
    - anywidget
    - ipywidgets
    - jinja2
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - rich >=14.2
    - scikit-learn
    - seaborn
    - skore-hub-project >=0.0.21
    - skore-local-project >=0.0.5
    - skore-mlflow-project >=0.0.3
    - skrub

test:
  imports:
    - skore
    - skore_hub_project
    - skore_local_project
    - skore_mlflow_project
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Track Your Data Science.
    Skore's open-source Python library accelerates ML model development with automated evaluation reports,
    smart methodological guidance, and comprehensive cross-validation analysis.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - thomass-dev
    - tuscland
