{% set name = "skore" %}
{% set version = "0.11.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: b7428e5497afe7a3e04a617c96e82d872923e359e2fad65230e7273e1b70048c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - IPython
    - anywidget
    - ipywidgets
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - rich
    - scikit-learn
    - seaborn
    - skore-hub-project
    - skore-local-project
    - skrub

test:
  imports:
    - skore
    - skore_hub_project
    - skore_local_project
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - mariesacksick
    - thomass-dev
    - tuscland
