{% set name = "skore" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: 8db1b44eca52622830f6d27e869098705c9fd23bb5158dced7b5d77c8151e124

build:
  entry_points:
    - skore = skore.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - diskcache
    - fastapi
    - joblib
    - matplotlib
    - numpy
    - pandas
    - plotly >=5,<6
    - pyarrow
    - rich
    - scikit-learn
    - skops
    - uvicorn

test:
  imports:
    - skore
  commands:
    - pip check
    - skore --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - augustebaum
    - glemaitre
    - MarieS-WiMLDS
    - sylvaincom
    - thomass-dev
    - tuscland
