{% set name = "skore" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: a24410ffb26b461c9b48d40c703242e4015b49ae01e73a91163d0df55d9100c1

build:
  entry_points:
    - skore = skore.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - diskcache
    - fastapi
    - pandas  # remove in 0.5.0
    - plotly >=5,<6
    - pyarrow
    - rich
    - skops
    - uvicorn

test:
  imports:
    - skore
  commands:
    - pip check
    - skore --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: Your scikit-learn Modeling Companion
  description: |
    skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - augustebaum
    - glemaitre
    - MarieS-WiMLDS
    - sylvaincom
    - thomass-dev
    - tuscland
