{% set name = "skore" %}
{% set version = "0.23.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: 6838b44fe0859bc676f199b049f47a0a3a1cbf59c9b70aadf0c0de67d761fd75

build:
  entry_points:
    # login
    - skore.plugins.login.hub = skore._plugins.hub.authentication.login:login
    # Project
    - skore.plugins.project.local = skore._plugins.local:Project
    - skore.plugins.project.hub = skore._plugins.hub.project.project:Project
    - skore.plugins.project.mlflow = skore._plugins.mlflow:Project

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - IPython
    - diskcache
    - httpx
    - ipywidgets
    - jinja2
    - joblib
    - matplotlib-base
    - mlflow >=2.20.4
    - numpy
    - orjson
    - pandas
    - platformdirs
    - plotly
    - pydantic
    - rich >=14.2
    - scikit-learn
    - scipy
    - seaborn
    - skrub >=0.9
    - skore-cli

test:
  imports:
    - skore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Track Your Data Science.
    Skore's open-source Python library accelerates ML model development with automated evaluation reports,
    smart methodological guidance, and comprehensive cross-validation analysis.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - jeromedockes
    - thomass-dev
