{% set name = "skore" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore-{{ version }}.tar.gz
  sha256: ea83a9fa2702e956c78e7ab3bea09ad4ed2c63b024cf81ba93c788727c1ce00b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - diskcache
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - rich
    - scikit-learn
    - skops
    # Need to pin sqlite for compatibility reason with diskcache
    # cf. https://github.com/probabl-ai/skore/issues/1353
    - sqlite <3.49

test:
  imports:
    - skore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - MarieSacksick
    - sylvaincom
    - thomass-dev
    - tuscland
